name: Build InfinityExpansion2

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew clean build --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: InfinityExpansion2-build
          path: build/libs/*.jar
